### PR TITLE
New title page

### PR DESCRIPTION
**Pull request by krawaller**
So here's a stab at a foundation for a new title page according to your ideas in #388, @wnr! 

Far from perfect, but, already an improvement?

@hkwaller and @litenjacob, any opinions? 

I'm considering
* adding arrow navs on top of the board so user can flip between games
* making games show their demos, so we don't just switch between static board positions 

newtitlepage

### CODE REVIEW

**Comment by wnr** [comment]
@krawaller I like it, well done! 😃  

I think the board looks a bit naked as it is right now. I would consider keeping the "Welcome text" on top of the board like before, and perhaps the "play" button on top as well. If we do that, then the first paragraph would disappear. Perhaps we can come up with some other text that naturally embeds the "browse" button? Perhaps a little explanation what "chess variants/abstract board games" is about for new users. Something along "Chessicals is a collection of simple games, visualised by using chess pieces. Some games are adaptations of ancient cultural games, and some are just made up by enthusiasts. [Button]" - but with your superior English haha 😁

**Comment by krawaller** [comment]
@wnr Excellent suggestions, again! Agreed, I will reinstate "Welcome" msg on top part of board, and move buttons to play the current game and browse all games to bottom part of board. Along with adding flip arrows to manually switch between games. And probably making individual games play through demos instead of just showing static setup.

Tried something else too; I added a "who am I" switcher between newbie and veteran content. Kind of cute, I think it works well?

image

image

(I'll change the newbie content to more explanatory stuff as you suggested once I've moved the other crap)

**Comment by krawaller** [comment]
Hey - I'm gonna move discussion on this to a dedicated Slack channel. Might be someone else wanna weigh in!

**Comment by krawaller** [comment]
@wnr This PR is already unwieldy enough - gonna merge it now, and we can do new PR:s for subsequent title page work!

**Comment by wnr** [comment]
@krawaller Sounds smart 👍

**Pull request merged**
