### PR TITLE
Fixed missing dependencies

### PR DESCRIPTION
**Pull request by wnr**
Noticed that a few packages were missing when I ran `npm install`. I added them as dev dependencies.

### CODE REVIEW

**Comment by krawaller** [comment]
Hmm - `mini-svg-data-uri` is only referred in the `graphics` module? Ah, but, if we initiate a command from another module (which we do now, the composite thing), it might still be unable to find it, so it can make sense to move it to the root.

But, if we do add it to the root dependencies, then we should remove it from `graphics`!

**Comment by wnr** [comment]
Ah, that makes sense. I'll move it 👍

**Comment by krawaller** [comment]
When exactly did you get into trouble with missing dependencies?

I tried on `master` to...

1. wipe all `node_modules` in the root and all module folders
1. `npm run installAll`
1. `npm run clean`
1. `npm run robot`

...and it seemed to work!

**Comment by wnr** [comment]
@krawaller I tried those steps now as well, and it worked correctly! I noticed that in your intro video https://www.youtube.com/watch?v=eikY_WlDmgs&feature=youtu.be&ab_channel=DavidWaller it says `npm install`. Perhaps I missed the `npm run installAll` and thought that some dependencies simply were missing. I'll close this PR :)

**Comment by krawaller** [comment]
Ooh, that’s right! I’m lying in the video.

Let that be a lesson for you, you shouldn’t believe everything you see on Youtube! :D

**Comment by wnr** [comment]
Haha 😂

**Pull request closed without merging**
